# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import resource_rc
import Login_sort as LS
import sys
from PyQt5.QtWidgets import QApplication
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QMargins, Qt

class Ui_Form(QtWidgets.QMainWindow):
    def __init__(self):
        QtWidgets.QMainWindow.__init__(self)
        self.setupUi(self)
        self.retranslateUi(self)

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(500, 400)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/test/用户.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        Form.setAccessibleName("")
        Form.setStyleSheet("*{\n"
"background:rgb(255, 255, 255);\n"
"font-size:15px;\n"
"font-style:MingLiU-ExtB;\n"
"}\n"
"\n"
"QLineEdit\n"
"{\n"
"    background:white;\n"
"    padding-left:10px ;\n"
"    padding-top:1px ;\n"
"    border-bottom-left-radius:10px;\n"
"    border-top-left-radius:10px;\n"
"    border-top-right-radius:10px;\n"
"    \n"
"    border-bottom-right-radius:10px;\n"
"    border: 1px solid rgb(209 , 209 , 209);\n"
"}\n"
"QLineEdit:hover\n"
"{\n"
"    padding-top:0px ;\n"
"    border: 1px solid rgb(21 , 131 , 221);\n"
"}\n"
"\n"
"\n"
"\n"
"QCheckBox{\n"
"background:rgba(85,170,255,0);\n"
"    color: rgb(0, 0, 0);\n"
"font-style:MingLiU-ExtB;\n"
"}\n"
"QLabel{\n"
"font-style:MingLiU-ExtB;\n"
"font-size:14px;\n"
"}\n"
"QComboBox\n"
"{\n"
"    background:white;\n"
"    padding-left:10px ;\n"
"    border-top-left-radius:10px;\n"
"    border-top-right-radius:10px;\n"
"    border-bottom-left-radius:10px;\n"
"    border-bottom-right-radius:10px;\n"
"    border: 1px solid rgb(209 , 209 , 209);\n"
"}\n"
"QComboBox:hover\n"
"{\n"
"    border: 1px solid rgb(21 , 131 , 221);\n"
"}\n"
"QComboBox QAbstractItemView::item\n"
"{\n"
"    height:40px;\n"
"}\n"
"QComboBox::down-arrow\n"
"{\n"
"    border-image:url(:/test/下箭头 (2).png);\n"
"    width:25px;\n"
"    height:25px;\n"
"}\n"
"QComboBox::down-arrow:hover\n"
"{\n"
"    border-image:url(:/test/下箭头 (2).png);\n"
"    width:30px;\n"
"    height:30px;\n"
"}\n"
"QComboBox::down-arrow:on\n"
"{\n"
"    border-image:url(:/test/下箭头 (2).png);\n"
"}\n"
"QComboBox::drop-down\n"
"{\n"
"    width:20px;\n"
"    background:transparent;\n"
"    padding-right:5px;\n"
"}\n"
"\n"
"")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(0, 0, 500, 400))
        self.frame.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 255, 255);\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_2.setEnabled(True)
        self.lineEdit_2.setGeometry(QtCore.QRect(90, 210, 321, 41))
        self.lineEdit_2.setStyleSheet("\n"
"color: rgb(0, 0, 0);")
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_2.setClearButtonEnabled(True)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.checkBox = QtWidgets.QCheckBox(self.frame)
        self.checkBox.setGeometry(QtCore.QRect(100, 260, 91, 19))
        self.checkBox.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 9pt \"宋体\";\n"
"background:transparent;")
        self.checkBox.setObjectName("checkBox")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(90, 310, 331, 51))
        self.pushButton.setStyleSheet("QPushButton\n"
"{\n"
"    border-radius:10px;\n"
"    background-color: rgb(42,166,244);\n"
"    font: 24pt \"黑体\";\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    \n"
"    border-radius:10px;\n"
"    background-color: rgb(135, 135, 135);\n"
"    font: 24pt \"黑体\";\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    \n"
"    border-radius:10px;\n"
"    background-color: rgb(255, 0, 0);\n"
"    font: 24pt \"黑体\";\n"
"}\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(350, 280, 72, 15))
        self.label.setStyleSheet("background:transparent;\n"
"color: rgb(0, 0, 255);\n"
"font: 9pt \"黑体\";")
        self.label.setObjectName("label")
        self.toolButton_2 = QtWidgets.QToolButton(self.frame)
        self.toolButton_2.setGeometry(QtCore.QRect(470, 0, 30, 30))
        self.toolButton_2.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.toolButton_2.setStyleSheet("background:transparent;\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/test/关闭.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_2.setIcon(icon1)
        self.toolButton_2.setObjectName("toolButton_2")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(169, 80, 171, 61))
        self.label_2.setStyleSheet("background:transparent;\n"
"font: 24pt \"黑体\";\n"
"color: rgb(136, 136, 136);")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(130, 370, 140, 16))
        self.label_3.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 9pt \"宋体\";\n"
"background:transparent;")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(268, 370, 31, 16))
        self.label_4.setStyleSheet("color: rgb(255, 51, 88);\n"
"\n"
"font: 9pt \"宋体\";\n"
"background:transparent;")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setEnabled(True)
        self.label_5.setGeometry(QtCore.QRect(300, 370, 51, 16))
        self.label_5.setAcceptDrops(False)
        self.label_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_5.setAutoFillBackground(False)
        self.label_5.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 9pt \"宋体\";\n"
"background:transparent;")
        self.label_5.setObjectName("label_5")
        self.comboBox = QtWidgets.QComboBox(self.frame)
        self.comboBox.setGeometry(QtCore.QRect(90, 160, 321, 41))
        self.comboBox.setAccessibleName("")
        self.comboBox.setStyleSheet("color: rgb(0, 0, 0);\n"
"")
        self.comboBox.setEditable(True)
        self.comboBox.setCurrentText("")
        self.comboBox.setMaxCount(2147483646)
        self.comboBox.setDuplicatesEnabled(False)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(0, 0, 500, 400))
        self.frame_2.setStyleSheet("image: url(:/test/榕创科技LOGO-02.png);\n"
"\n"
"background-color: rgb(255, 255, 255,0);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.frame_2.raise_()
        self.checkBox.raise_()
        self.comboBox.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.pushButton.raise_()
        self.toolButton_2.raise_()
        self.lineEdit_2.raise_()

        self.retranslateUi(Form)
        self.comboBox.setCurrentIndex(-1)
        self.toolButton_2.clicked.connect(Form.close) # type: ignore
        self.pushButton.clicked.connect(lambda :self.Log())
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "登录"))
        Form.setWindowFlags(Qt.FramelessWindowHint)
        Form.setAttribute(Qt.WA_TranslucentBackground)

        self.lineEdit_2.setPlaceholderText(_translate("Form", "密码"))
        self.checkBox.setText(_translate("Form", "自动登录"))
        self.pushButton.setText(_translate("Form", "登录"))
        self.label.setText(_translate("Form", "忘记密码？"))
        self.toolButton_2.setText(_translate("Form", "close"))
        self.label_2.setText(_translate("Form", "欢迎登录"))
        self.label_3.setText(_translate("Form", "你还没有账号？那就"))
        self.label_4.setText(_translate("Form", "注册"))
        self.label_5.setText(_translate("Form", "一个吧~"))
        self.comboBox.lineEdit().setPlaceholderText(_translate("Form", "账号"))
        self.comboBox.setItemText(0, _translate("Form", "qweqe"))
        self.comboBox.setItemText(1, _translate("Form", "qweqeqwe"))

    def Log(self):
        self.id = self.comboBox.lineEdit().text()
        self.pwd = self.lineEdit_2.text()
        LS.Login(self.id,self.pwd)


if __name__ == '__main__':
    app=QApplication(sys.argv)
    ex=Ui_Form()
    ex.show()
    sys.exit(app.exec_())
